<h2>Import necessary libraries</h2>

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

<h2>Read csv data file</h2>

In [24]:
data = pd.read_csv('MOCK_DATA.csv')

<h1>Set x and y (dependent and independent variables)</h1>

In [121]:
x = data.iloc[:, [1, 4]]
y = data.iloc[:, 3]

<h2>Remove rows with NaN values</h2>

In [122]:
# Drop NaN values in x
x = x.dropna()

# Replace NaN values in y with mean
y = y.fillna(y.mean())

<h2>Convert non-numerical values to numbers - Independent Variables</h2>

In [124]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0, 1])], 
                                     remainder='passthrough')
x = np.array(ct.fit_transform(x.values))

In [126]:
# print(np.unique(x))
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
